[package]
name = "kb-drums"
version = "0.1.0"
authors = ["insomnimus <insomnimus19@gmail.com>"]
edition = "2018"

[[bin]]
name = "rt-drums"
path = "src/main.rs"

[dependencies]
crossterm = "0.19.0"
midir = {version="0.7.0", features=["winrt"]}
