pub mod app;
pub mod config;

pub(crate) const DRUMS: &[(&str, u8)] = &[
	("acoustic-bass-drum", 35),
	("bass-drum-1", 36),
	("side-stick", 37),
	("acoustic-snare", 38),
	("hand-clap", 39),
	("electric-snare", 40),
	("low-floor-tom", 41),
	("closed-hi-hat", 42),
	("high-floor-tom", 43),
	("pedal-hi-hat", 44),
	("low-tom", 45),
	("open-hi-hat", 46),
	("low-mid-tom", 47),
	("hi-mid-tom", 48),
	("crash-cymbal-1", 49),
	("high-tom", 50),
	("ride-cymbal-1", 51),
	("chinese-cymbal", 52),
	("ride-bell", 53),
	("tambourine", 54),
	("splash-cymbal", 55),
	("cowbell", 56),
	("crash-cymbal-2", 57),
	("vibraslap", 58),
	("ride-cymbal-2", 59),
	("hi-bongo", 60),
	("low-bongo", 61),
	("mute-hi-conga", 62),
	("open-hi-conga", 63),
	("low-conga", 64),
	("high-timbale", 65),
	("low-timbale", 66),
	("high-agogo", 67),
	("low-agogo", 68),
	("cabasa", 69),
	("maracas", 70),
	("short-whistle", 71),
	("long-whistle", 72),
	("short-guiro", 73),
	("long-guiro", 74),
	("claves", 75),
	("hi-wood-block", 76),
	("low-wood-block", 77),
	("mute-cuica", 78),
	("open-cuica", 79),
	("mute-triangle", 80),
	("open-triangle", 81),
];
