pub mod app;
pub mod config;

pub(crate) const DRUMS: &[(&str, u8)] = &[
	("acoustic_bass_drum", 35),
	("bass_drum_1", 36),
	("side_stick", 37),
	("acoustic_snare", 38),
	("hand_clap", 39),
	("electric_snare", 40),
	("low_floor_tom", 41),
	("closed_hi-hat_", 42),
	("high_floor_tom", 43),
	("pedal_hi-hat", 44),
	("low_tom", 45),
	("open_hi-hat_", 46),
	("low-mid_tom", 47),
	("hi-mid_tom", 48),
	("crash_cymbal_1", 49),
	("high_tom", 50),
	("ride_cymbal_1", 51),
	("chinese_cymbal_", 52),
	("ride_bell", 53),
	("tambourine", 54),
	("splash_cymbal_", 55),
	("cowbell", 56),
	("crash_cymbal_2", 57),
	("vibraslap", 58),
	("ride_cymbal_2", 59),
	("hi_bongo", 60),
	("low_bongo", 61),
	("mute_hi_conga", 62),
	("open_hi_conga", 63),
	("low_conga", 64),
	("high_timbale", 65),
	("low_timbale", 66),
	("high_agogo", 67),
	("low_agogo", 68),
	("cabasa", 69),
	("maracas", 70),
	("short_whistle", 71),
	("long_whistle", 72),
	("short_guiro", 73),
	("long_guiro", 74),
	("claves", 75),
	("hi_wood_block", 76),
	("low_wood_block", 77),
	("mute_cuica", 78),
	("open_cuica", 79),
	("mute_triangle", 80),
	("open_triangle", 81),
];
